### ISSUE TITLE
Emitted types are incorrect

### ISSUE THREAD

**Issue by vincentbriglia** [poppinss/colors#2]
## Description

TypeScript types generated for @poppinss/colors are incorrect and break the TypeScript compiler  

## Package version
@poppinss/cliui@1.0.3
@poppinss/colors@2.0.1

typescript 3.9.7
node 14.5.0

## Error Message & Stack Trace

52 errors for each custom defined color:
```
node_modules/@poppinss/colors/build/src/Base.d.ts:18:5 - error TS2416: Property 'black' in type 'Colors' is not assignable to the same property in base type 'Kleur'.
  Type '{ (): this; (text: string): string; }' is not assignable to type 'Color'.
    Type 'this' is not assignable to type 'string'.
      Type 'Colors' is not assignable to type 'string'.

18     black(): this;
       ~~~~~
```

## Relevant Information

Started using cliui in a project to see how it worked, found that it was throwing this error, so started a self-contained project with @poppinss/cliui with the following package.json: 

```
{
  "name": "poppins",
  "version": "1.0.0",
  "description": "",
  "main": "lib/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@poppinss/colors": "2.0.1"
  },
  "devDependencies": {
    "typescript": "3.9.7"
  }
}
```

and an index.ts

```
import { Colors } from '@poppinss/colors';

console.log(Colors);
```

and compiled with typescript, got the same error.

**Comment by thetutlage** [comment]
Seems like you are running Typescript in strict mode. I don't use/code around the strict mode.

**Comment by thetutlage** [comment]
Closing since not actionable
